version: '3.8'

services:
  web:
    build: .
    ports:
      - 3000:3000
    networks:
      - express-mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/test

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - express-mongo

networks:
  express-mongo:
    driver: bridge
